#!/usr/bin/perl

use Modern::Perl;

use FindBin qw($Bin);
use File::Spec;
use Test::More;

my $plugin_root = File::Spec->catdir( $Bin, '..' );

sub read_file {
    my ($relative_path) = @_;

    my $path = File::Spec->catfile( $plugin_root, split m{/}, $relative_path );
    open my $fh, '<:encoding(UTF-8)', $path or die "Cannot read $path: $!";
    my $content = do { local $/; <$fh> };
    close $fh;

    return $content;
}

my $plugin_pm = read_file('Koha/Plugin/Fi/KohaSuomi/Editx.pm');
my $configure = read_file('Koha/Plugin/Fi/KohaSuomi/Editx/configure.tt');
my $tool = read_file('Koha/Plugin/Fi/KohaSuomi/Editx/tool.tt');
my $breadcrumbs = read_file('Koha/Plugin/Fi/KohaSuomi/Editx/includes/editx_breadcrumbs.inc');
my $css = read_file('Koha/Plugin/Fi/KohaSuomi/Editx/static_files/editx.css');
my $local_build = read_file('local_build.sh');
my $install_sql = read_file('installation/create_tables.sql');
my $fetch_sftp = read_file('Koha/Plugin/Fi/KohaSuomi/Editx/cronjobs/fetch_editx_sftp.sh');
my $order_processor = read_file('Koha/Plugin/Fi/KohaSuomi/Editx/Procurement/OrderProcessor.pm');
my $unofficial_instance_env = 'KOHA' . '_INSTANCE';

like( $plugin_pm, qr{our\s+\$VERSION\s*=\s*"0\.0\.2";}, 'Plugin version is hardcoded in source instead of kept as a release placeholder' );
unlike( $plugin_pm, qr{\{VERSION\}}, 'Plugin source does not expose a raw version placeholder' );
like( $local_build, qr{SOURCE_VERSION=.*our\\s\+\\\$VERSION}, 'Local build reads the fallback package version from the plugin source' );
like( $local_build, qr{No version tag found, using source version}, 'Local build reports source-version fallback when no tag exists' );
like( $plugin_pm, qr{sub\s+tool\s*\{}, 'Plugin exposes a Koha tool page' );
like( $plugin_pm, qr{\$method\s*\|\|=\s*'tool'}, 'Plugin method URL defaults to the tool page' );
like( $plugin_pm, qr{tool_href\s*=>\s*\$self->plugin_method_url\('tool'\)}, 'Configure template receives tool_href' );
like( $plugin_pm, qr{sub\s+static_routes\s*\{[\s\S]+mbf_read\('staticapi\.json'\)}, 'Plugin exposes Koha static routes for assets' );
unlike( $plugin_pm, qr{sub\s+api_routes\s*\{}, 'Plugin does not add custom API routes for assets' );
unlike( $plugin_pm, qr{static_asset_url}, 'Plugin does not build stylesheet URLs in the controller' );
like( $plugin_pm, qr{plugin_display_version\s*=>\s*\$self->plugin_display_version\(\)}, 'Plugin still passes the display version to templates' );
like( $plugin_pm, qr{last_configured_by\s*=>\s*scalar\s+\$self->_last_configured_by_context\(\)}, 'Optional last configured patron context is passed to templates in scalar context' );
like( $plugin_pm, qr{last_upgraded\s*=>\s*scalar\s+\$self->retrieve_data\('last_upgraded'\)}, 'Optional last upgraded value is passed to templates in scalar context' );
unlike( $plugin_pm, qr{\Q$unofficial_instance_env\E}, 'Plugin Perl code does not treat unofficial instance environment as a Koha instance source' );
unlike( $plugin_pm, qr{editx_debug|_template_debug_comment|editx_debug_comment}, 'Plugin Perl code does not keep deployment debug comment hooks' );
like( $plugin_pm, qr{export_mapping_csv}, 'Configure controller handles ProductForm mapping CSV export as an explicit POST action' );
like( $plugin_pm, qr{sub\s+_uploaded_productform_mapping_csv\s*\{}, 'Configure controller reads ProductForm mapping CSV imports from uploaded files' );
like( $plugin_pm, qr{sub\s+_output_productform_mapping_csv\s*\{}, 'Configure controller can return ProductForm mapping CSV as a download' );
like( $plugin_pm, qr{manual_run_available}, 'Tool template receives manual action availability context' );
like( $plugin_pm, qr{manual_run_confirmation}, 'Tool template receives manual run confirmation context' );
like( $plugin_pm, qr{manual_stage\s*=>\s*\$manual_stage}, 'Tool template receives staged workflow context' );
like( $plugin_pm, qr{manual_stage_sources}, 'Tool template receives staged workflow source choices' );
like( $plugin_pm, qr{sub\s+_manual_sync_confirmation\s*\{}, 'Plugin builds manual run confirmation data' );
like( $plugin_pm, qr{sub\s+_manual_selected_sftp_sources\s*\{}, 'Plugin filters staged manual checks to selected SFTP sources' );
like( $plugin_pm, qr{sub\s+_manual_stage_check_remote\s*\{}, 'Plugin can check remote SFTP files as stage one' );
like( $plugin_pm, qr{sub\s+_manual_stage_resume\s*\{}, 'Plugin can resume a staged workflow after a redirect-safe GET reload' );
like( $plugin_pm, qr{sub\s+_manual_stage_download_selected\s*\{}, 'Plugin can download selected remote files into manual staging' );
like( $plugin_pm, qr{sub\s+_manual_stage_import_selected\s*\{}, 'Plugin can import selected staged files' );
like( $plugin_pm, qr{ImportRunner->new\(\s*\{\s*echo\s*=>\s*0\s*\}\s*\)->run_file_paths}, 'Manual staged web import suppresses runner console echo before rendering the Koha response' );
like( $plugin_pm, qr{sub\s+_manual_stage_preview_file\s*\{}, 'Plugin builds EDItX previews for staged files' );
like( $plugin_pm, qr{manual keeps remote}, 'Manual staged downloads do not archive or delete remote files' );
like( $plugin_pm, qr{print\s+\$cgi->redirect\(\s*\$self->_manual_stage_url\(\s*\$manual_stage->\{run_id\},\s*'downloaded'\s*\)\s*\)}, 'Stage download POST redirects to a reload-safe GET page' );
like( $plugin_pm, qr{print\s+\$cgi->redirect\(\s*\$self->_manual_stage_url\(\s*\$manual_stage->\{run_id\},\s*'imported'\s*\)\s*\)}, 'Stage import POST redirects to a reload-safe GET page' );
like( $plugin_pm, qr{recommended_import_paths}, 'Configure template receives recommended import path examples' );
like( $plugin_pm, qr{substr\( \$message, 0, 397 \).*substr\( \$message, -398 \)}s, 'Long manual sync diagnostics preserve both beginning and end of captured output' );
like( $plugin_pm, qr{output_html\(\s*\$template->output\(\),\s*undef,\s*undef,\s*undef,\s*Koha::Plugin::Fi::KohaSuomi::Editx::FlashCookie->merge_cookies}s, 'Configure page passes flash cookies as output_html cookies, not extra options' );
like( $plugin_pm, qr{get_qualified_table_name\('procurement_file'\)}, 'Plugin install uses a qualified procurement_file table' );
like( $plugin_pm, qr{sub\s+install\(\)[\s\S]+_install_or_upgrade_tables\( migrate_legacy => 0 \)}, 'Plugin install creates qualified tables without legacy migration' );
like( $plugin_pm, qr{sub\s+upgrade[\s\S]+_install_or_upgrade_tables\( migrate_legacy => 1 \)}, 'Plugin upgrade enables legacy table migration' );
like( $plugin_pm, qr{_migrate_legacy_procurement_file_table}, 'Plugin upgrade can migrate legacy procurement_file data' );
like( $plugin_pm, qr{sub\s+uninstall\(\)[\s\S]+editx_map_productform map_productform}, 'Plugin uninstall cleans legacy ProductForm table names as leftover plugin data' );
like( $install_sql, qr{CREATE TABLE IF NOT EXISTS `koha_plugin_fi_kohasuomi_editx_map_productform`}, 'Install SQL still creates the ProductForm mapping table' );
unlike( $install_sql, qr{INSERT INTO\s+koha_plugin_fi_kohasuomi_editx_map_productform}i, 'Install SQL does not seed ProductForm mappings' );
unlike( $install_sql, qr{28VRK|28VRKLN|14VRK|EILAINATA}, 'Install SQL does not contain KohaSuomi-local itemtype seeds' );

like( $breadcrumbs, qr{href="\[%\s*tool_href\s*\|\s*html\s*%\]">EDItX plugin</a>}, 'Breadcrumb plugin root points to the tool page' );
like( $breadcrumbs, qr{active_method\s*!=\s*'configure'}, 'Breadcrumb configure shortcut is hidden on the configure page' );
like( $breadcrumbs, qr{href="\[%\s*configure_href\s*\|\s*html\s*%\]">Configure</a>}, 'Breadcrumb includes a configure shortcut on operational pages' );

unlike( $configure, qr{run_sync_now}, 'Configure page has no manual sync action input' );
unlike( $configure, qr{Download and import now}, 'Configure page has no manual download/import button' );
unlike( $configure, qr{Manual run result}, 'Configure page has no manual run result block' );
like( $configure, qr{href="\[%\s*tool_href\s*\|\s*html\s*%\]">Cancel</a>}, 'Configure cancel returns to the tool page' );
like( $configure, qr{\[%\s*SET\s+footerjs\s*=\s*1\s*%\]}, 'Configure page enables Koha footer JavaScript before using jsinclude' );
like( $configure, qr{Configure EDItX plugin v\[%\s*plugin_display_version\s*\|\s*html\s*%\]}, 'Configure page renders the controller-supplied display version' );
like( $configure, qr{<link rel="stylesheet" href="/api/v1/contrib/editx/static/static_files/editx\.css" />}, 'Configure page hardcodes the stable Koha plugin static CSS URL' );
unlike( $configure, qr{editx_debug|editx_debug_comment|EDItX debug}, 'Configure page does not keep deployment debug comments in source' );
unlike( $configure, qr{Configure the nightly SFTP download, import folders, EDItX processing rules, notifications, and ONIX ProductForm mappings\.}, 'Configure page header does not present email notifications as a main setup area' );
unlike( $configure, qr{SFTP sources YAML}, 'Configure page does not expose SFTP YAML editing' );
like( $configure, qr{id="editx-sftp-sources-table"\s+class="editx-config-table editx-sftp-sources-table"[\s\S]+Source name[\s\S]+Remote folder / Pattern[\s\S]+data-editx-sftp-source-row="1"[\s\S]+id="editx-add-sftp-source"}, 'Configure page edits SFTP sources as two-line source rows' );
like( $configure, qr{data-editx-sftp-column="host"[\s\S]+placeholder="sftp\.vendor\.example"[\s\S]+data-editx-sftp-column="port"[\s\S]+placeholder="22"}, 'SFTP source fields include concrete placeholders for host and port' );
like( $configure, qr{placeholder="/out/editx"[\s\S]+data-editx-sftp-column="remote"[\s\S]+placeholder="\*\.xml"[\s\S]+data-editx-sftp-column="remote"}, 'SFTP remote folder and pattern fields include concrete placeholders' );
like( $configure, qr{name="sftp_id"\s+type="text"[\s\S]+pattern="\[A-Za-z0-9_\]\+"[\s\S]+title="Use letters, numbers, and underscores only; no spaces\."}, 'SFTP source name has a browser-visible format validator' );
like( $configure, qr{name="sftp_pattern"\s+type="text"[\s\S]+placeholder="\*\.xml"[\s\S]+data-editx-sftp-column="remote"}, 'SFTP filename pattern keeps a concrete placeholder' );
unlike( $configure, qr{name="sftp_pattern"[^>]+pattern=}, 'SFTP filename pattern does not keep a browser regex validator' );
like( $configure, qr{data-default-identity-file="\[%\s*recommended_sftp_paths\.identity_file\s*\|\s*html\s*%\]"[\s\S]+data-default-known-hosts-file="\[%\s*recommended_sftp_paths\.known_hosts_file\s*\|\s*html\s*%\]"}, 'SFTP source table carries recommended path defaults for new rows' );
like( $configure, qr{name="sftp_port"\s+type="text"\s+inputmode="numeric"\s+pattern="6553\[0-5\]\|655\[0-2\]\[0-9\]\|65\[0-4\]\[0-9\]\{2\}\|6\[0-4\]\[0-9\]\{3\}\|\[1-5\]\[0-9\]\{4\}\|\[1-9\]\[0-9\]\{0,3\}"\s+maxlength="5"[\s\S]+title="Use a TCP port number from 1 to 65535\."}, 'SFTP port is a text input with a browser-visible TCP port validator' );
like( $configure, qr{id="authoriser"\s+name="authoriser"\s+type="text"\s+inputmode="numeric"\s+pattern="\[0-9\]\*"}, 'Authoriser borrowernumber is a text input with numeric hints instead of a spinner field' );
unlike( $configure, qr{type="number"}, 'Configure page does not use browser spinner number inputs' );
like( $configure, qr{name="sftp_identity_file"\s+type="text"\s+value="\[%\s*IF\s+source\.identity_file\s*%\]\[%\s*source\.identity_file\s*\|\s*html\s*%\]\[%\s*ELSE\s*%\]\[%\s*recommended_sftp_paths\.identity_file\s*\|\s*html\s*%\]}, 'Existing SFTP rows fall back to the recommended identity path when empty' );
like( $configure, qr{name="sftp_known_hosts_file"\s+type="text"\s+value="\[%\s*IF\s+source\.known_hosts_file\s*%\]\[%\s*source\.known_hosts_file\s*\|\s*html\s*%\]\[%\s*ELSE\s*%\]\[%\s*recommended_sftp_paths\.known_hosts_file\s*\|\s*html\s*%\]}, 'Existing SFTP rows fall back to the recommended known-hosts path when empty' );
like( $configure, qr{name="sftp_identity_file"\s+type="text"\s+value="\[%\s*recommended_sftp_paths\.identity_file\s*\|\s*html\s*%\]"[\s\S]+name="sftp_known_hosts_file"\s+type="text"\s+value="\[%\s*recommended_sftp_paths\.known_hosts_file\s*\|\s*html\s*%\]"}, 'Initial blank SFTP row is prefilled with recommended key and known-hosts paths' );
unlike( $configure, qr{Known hosts setup|editx-known-hosts-hash-toggle|Hash hostnames in known_hosts|ssh-keyscan}, 'Configure page does not expose known-hosts setup or hostname hashing UI' );
unlike( $configure, qr{knownHostsHashToggle|knownHostsCommandForRow|renderKnownHostsCommands}, 'Configure JavaScript does not keep known-hosts hashing helpers' );
like( $configure, qr{querySelector\("tbody\[data-editx-sftp-source-row\]"\)[\s\S]+closest\("tbody\[data-editx-sftp-source-row\]"\)}, 'Configure JavaScript treats each two-line SFTP source body as one row group' );
like( $configure, qr{function\s+setActiveSftpHeader[\s\S]+is-active-sftp-header[\s\S]+focusin[\s\S]+dataset\.editxSftpColumn}, 'Configure JavaScript highlights the matching SFTP header while a field is focused' );
like( $configure, qr{function\s+validateSftpSourceNames[\s\S]+input\.setCustomValidity\("Source name must be unique\."\)}, 'Configure JavaScript validates duplicate SFTP source names before submit' );
like( $configure, qr{data-editx-collapsible-storage="editx\.configure\.legacyEmailNotifications\.v1"[\s\S]+Legacy email notification scripts[\s\S]+The nightly EDItX synchronization does not send email[\s\S]+id="notification_mailto"[\s\S]+id="notification_mailfrom"}, 'Configure page keeps email notification settings in a collapsed legacy helper section' );
like( $configure, qr{Runtime and plugin status[\s\S]+data-editx-collapsible-storage="editx\.configure\.legacyEmailNotifications\.v1"}, 'Configure page places legacy email settings below runtime and plugin status' );
unlike( $configure, qr{<legend>Failure notifications</legend>}, 'Configure page does not show failure notifications as a primary librarian-facing section' );
like( $configure, qr{id="editx-productform-table"[\s\S]+name="edit_mapping_onix_code"[\s\S]+name="delete_mapping_row"}, 'Configure page renders ProductForm mappings with row-level edit and delete actions' );
like( $configure, qr{<tfoot>[\s\S]+id="add_mapping_onix_code"[\s\S]+name="add_mapping_row"[\s\S]+</tfoot>}, 'Configure page adds ProductForm mapping rows inside the mapping table footer' );
like( $configure, qr{enctype="multipart/form-data"}, 'Configure form can upload ProductForm mapping CSV files' );
like( $configure, qr{id="mapping_csv_file"[\s\S]+name="import_mapping_csv"[\s\S]+name="export_mapping_csv"}, 'Configure page imports ProductForm mappings from a CSV file and exports them by POST' );
unlike( $configure, qr{id="mapping_csv_export"}, 'Configure page does not render the ProductForm mapping CSV in the HTML body' );
like( $configure, qr{class="editx-code-example editx-code-example-watermark"\s+data-editx-watermark="Example"}, 'CSV import/export sample is explicitly marked as an example' );
like( $configure, qr{data-editx-partial-table="1"[\s\S]+editx-table-expander[\s\S]+editx-partial-table-toggle}, 'ProductForm mapping table uses a centered expander control' );
like( $configure, qr{data-editx-collapsible-storage="editx\.configure\.runtimeLogging\.v1"}, 'Runtime logging section has persisted collapse state' );
like( $configure, qr{data-editx-collapsible-default="collapsed"}, 'Runtime logging section is collapsed by default' );
like( $configure, qr{Runtime and plugin status}, 'Runtime section title includes plugin status' );
like( $configure, qr{class="editx-runtime-status-list"[\s\S]+class="editx-runtime-field-row"[\s\S]+class="editx-runtime-field-row editx-plugin-status"}, 'Runtime section uses plugin-owned layout classes instead of raw Koha row labels' );
like( $configure, qr{Last updated by[\s\S]+last_configured_by\.href[\s\S]+last_configured_by\.label}, 'Configure page links the last configuration editor by name when available' );
unlike( $configure, qr{Plugin settings were last updated by borrowernumber}, 'Configure page no longer shows raw last-updated borrowernumber text' );
like( $configure, qr{window\.localStorage}, 'Configure page persists the runtime logging collapse state in localStorage' );
unlike( $configure, qr{hidden="hidden"}, 'Runtime logging collapsible does not rely on a hidden attribute timer' );
like( $configure, qr{Recommended instance-owned base}, 'Configure page explains the recommended import folder base' );
like( $configure, qr{placeholder="\[%\s*recommended_import_paths\.tmp\s*\|\s*html\s*%\]"}, 'Configure page shows an instance-aware tmp folder placeholder' );
like( $configure, qr{recommended_import_paths\.failed_archived}, 'Configure page shows an instance-aware failed archive example' );
unlike( $configure, qr{editx-folder-flow}, 'Configure page does not render the old folder flow badges' );
like( $css, qr{\.editx-collapsible\.is-collapsed\s+\.editx-collapsible-body}, 'CSS hides collapsed runtime logging content' );
like( $css, qr{\.editx-runtime-field-row\s*\{[\s\S]+grid-template-columns:\s*16rem minmax\(0, 1fr\);}, 'CSS gives runtime status rows their own aligned grid' );
like( $css, qr{\.editx-config-form fieldset\.rows \.editx-runtime-field-row > select\s*\{[\s\S]+width:\s*auto;}, 'CSS keeps the runtime log level select compact' );
like( $css, qr{\.editx-config-form::after\s*\{[\s\S]+clear:\s*both;[\s\S]+display:\s*block;}, 'CSS contains Koha floated fieldsets inside the configure form page section' );
like( $configure, qr{class="editx-runtime-log-block"[\s\S]+class="editx-runtime-log-toolbar"[\s\S]+id="runtime_log_tail"}, 'Runtime log toolbar and textarea share one width container' );
like( $css, qr{\.editx-runtime-log-block\s*\{[\s\S]+display:\s*inline-block;[\s\S]+width:\s*auto;}, 'CSS lets the runtime log block shrink-wrap the textarea width' );
like( $css, qr{\.editx-runtime-log-toolbar\s*\{[\s\S]+width:\s*100%;}, 'CSS aligns the runtime log toolbar to the shared log block width' );
like( $css, qr{\.editx-config-form textarea\.editx-runtime-log-tail\s*\{[\s\S]+max-width:\s*100%;[\s\S]+width:\s*100%;}, 'CSS overrides the generic textarea cap for the runtime log textarea' );
like( $css, qr{\.editx-config-form textarea\.editx-runtime-log-tail\.editx-runtime-log-tail-wrapped\s*\{[\s\S]+white-space:\s*pre-wrap;}, 'CSS keeps runtime log wrapping stronger than the base textarea rule' );
like( $css, qr{\.editx-partial-table-wrap}, 'CSS supports partially collapsed table editors' );
like( $css, qr{\.editx-import-folders-table\s*\{[\s\S]+display:\s*inline-table;[\s\S]+width:\s*max-content;}, 'CSS keeps the import folders table shrink-wrapped to its content' );
like( $css, qr{\.editx-sftp-sources-table\s*\{[\s\S]+min-width:\s*58rem;[\s\S]+table-layout:\s*fixed;[\s\S]+width:\s*100%;}, 'CSS gives the two-line SFTP source table a compact fixed layout' );
like( $css, qr{\.editx-sftp-remote-pattern\s*\{[\s\S]+grid-template-columns:\s*minmax\(0, 1fr\) minmax\(6rem, 8rem\);}, 'CSS keeps remote folder and pattern compact inside one SFTP source cell' );
like( $css, qr{\.editx-sftp-sources-table thead th\.is-active-sftp-header\s*\{[\s\S]+rgba\(0, 123, 186, 0\.12\);}, 'CSS gives focused SFTP fields a quiet matching header highlight' );
like( $css, qr{\.editx-code-example-watermark::before\s*\{[\s\S]+content:\s*attr\(data-editx-watermark\);[\s\S]+text-transform:\s*uppercase;}, 'CSS renders CSV examples with a quiet background watermark' );
like( $css, qr{\.editx-config-form fieldset\.rows \.editx-inline-check\s*\{[\s\S]+display:\s*inline-flex;}, 'CSS keeps inline checkbox helpers out of Koha row-label layout' );
like( $css, qr{\.editx-productform-table\s*\{[\s\S]+width:\s*auto;}, 'CSS keeps the ProductForm mapping editor compact' );
unlike( $css, qr{editx-upgrade-status}, 'CSS does not keep the old standalone plugin status block styles' );
unlike( $css, qr{editx-folder-flow}, 'CSS does not keep unused folder flow badge styles' );
unlike( $css, qr{editx-example-grid}, 'CSS does not keep unused example grid styles' );
unlike( $css, qr{editx-known-hosts-helper}, 'CSS does not keep unused known-hosts helper styles' );

like( $tool, qr{active_text='Operations'\s+active_method='tool'}, 'Tool page marks the Operations breadcrumb active' );
like( $tool, qr{\[%\s*SET\s+footerjs\s*=\s*1\s*%\]}, 'Tool page enables Koha footer JavaScript before using jsinclude' );
like( $tool, qr{EDItX plugin v\[%\s*plugin_display_version\s*\|\s*html\s*%\]}, 'Tool page renders the controller-supplied display version' );
like( $tool, qr{<link rel="stylesheet" href="/api/v1/contrib/editx/static/static_files/editx\.css" />}, 'Tool page hardcodes the stable Koha plugin static CSS URL' );
unlike( $tool, qr{editx_debug|editx_debug_comment|EDItX debug}, 'Tool page does not keep deployment debug comments in source' );
like( $tool, qr{\[%\s+USE\s+raw\s+%\]}, 'Tool page loads Koha raw plugin before using template filters' );
like( $tool, qr{Staged manual workflow}, 'Tool page renders staged manual workflow' );
like( $tool, qr{Stage 1: Check remote files}, 'Tool page starts staged workflow by checking remote files' );
like( $tool, qr{\[%\s+UNLESS\s+manual_run_confirmation\s+%\]\s*<div class="page-section editx-staged-workflow">}, 'Tool page hides first-screen staged controls while showing confirmation details' );
like( $tool, qr{\[%\s+UNLESS\s+manual_stage\s+%\][\s\S]+name="review_stage_check_remote"\s+value="1"[\s\S]+\[%\s+END\s+%\]}, 'Tool page routes stage-one action through a review step while no staged workflow is active' );
like( $tool, qr{name="manual_source_id"}, 'Tool page lets staged manual runs scope the SFTP sources before checking remote files' );
like( $tool, qr{Fix SFTP configuration before using the staged workflow[\s\S]+Stage 1: Check remote files}, 'Tool page keeps staged configuration warning before the disabled stage-one action' );
like( $tool, qr{name="stage_download_selected"\s+value="1"}, 'Tool page can download selected remote files' );
like( $tool, qr{Download selected</button>\s*<a class="btn btn-default" href="\[%\s*tool_href\s*\|\s*html\s*%\]">Cancel</a>}, 'Remote-file stage offers a cancel link beside the download action' );
like( $tool, qr{name="remote_file"}, 'Tool page renders remote file selection checkboxes' );
like( $tool, qr{Downloaded EDItX preview}, 'Tool page renders downloaded file preview' );
like( $tool, qr{name="stage_import_selected"\s+value="1"}, 'Tool page can import selected staged files' );
like( $tool, qr{Import selected</button>\s*<a class="btn btn-default" href="\[%\s*tool_href\s*\|\s*html\s*%\]">Cancel</a>}, 'Downloaded-preview stage offers a cancel link beside the import action' );
like( $tool, qr{name="stage_file"}, 'Tool page renders staged file selection checkboxes' );
like( $tool, qr{file\.status\s+==\s+'valid'\s+&&\s+file\.duplicate_status\s+!=\s+'already imported'}, 'Tool page preselects only valid non-duplicate staged files for import' );
like( $tool, qr{Notice / Total}, 'Tool page combines notice and total preview columns' );
like( $tool, qr{Seller / Vendor IDs}, 'Tool page combines seller and vendor id preview columns' );
like( $tool, qr{Lines / Copies}, 'Tool page combines line and copy preview columns' );
like( $tool, qr{data-editx-check-all}, 'Tool page provides select-all checkboxes for staged tables' );
like( $tool, qr{Check remote files again}, 'Tool page offers a restart action after a staged import result' );
like( $tool, qr{href="\[%\s*tool_href\s*\|\s*html\s*%\]">Return to start</a>}, 'Tool page lets staff return from the staged import result to the start screen' );
like( $tool, qr{No remote EDItX files matched the configured SFTP sources[\s\S]+Check remote files again[\s\S]+Return to start}, 'Tool page gives explicit actions when no remote staged files match' );
unlike( $tool, qr{name="review_sync_now"\s+value="1"}, 'Tool page does not route the full-chain manual sync through a review POST action' );
like( $tool, qr{name="run_sync_now"\s+value="1"}, 'Tool page exposes the manual sync POST action' );
like( $tool, qr{Run full download and import}, 'Tool page starts the full-chain manual sync directly' );
like( $tool, qr{\[%\s+UNLESS\s+manual_run_confirmation\s+\|\|\s+manual_stage\s+%\][\s\S]+<form method="post" class="page-section editx-manual-sync-form">}, 'Tool page hides the full-chain shortcut while a staged workflow is active' );
like( $tool, qr{editx-or-separator[\s\S]+OR[\s\S]+editx-manual-sync-form}, 'Tool page separates the staged and full-chain actions with an OR divider' );
like( $tool, qr{manual_run_confirmation\.title}, 'Tool page renders manual confirmation titles from the controller' );
like( $tool, qr{name="\[%\s*manual_run_confirmation\.input_name\s*\|\s*html\s*%\]"}, 'Tool page posts the controller-selected confirmation action' );
like( $tool, qr{manual_run_confirmation\.button_label}, 'Tool page renders the controller-selected confirmation button' );
unlike( $tool, qr{onclick="return confirm}, 'Tool page does not rely on a browser confirm prompt for manual sync' );
like( $tool, qr{Acquisition result}, 'Tool page renders acquisition result links after imports' );
like( $tool, qr{No new acquisition order lines were found for this import}, 'Tool page avoids batch-specific wording for empty acquisition results' );
like( $tool, qr{manual_sync_result\.history_url}, 'Tool page links empty manual results to acquisition order search' );
unlike( $tool, qr{/cgi-bin/koha/acqui/acqui-home\.pl}, 'Tool page does not link empty manual results to the general acquisitions home page' );
like( $tool, qr{nightly_sync_enabled}, 'Tool page shows read-only nightly automation status' );
like( $tool, qr{href="\[%\s*configure_href\s*\|\s*html\s*%\]">Configure</a>}, 'Tool page links to configuration' );
like( $tool, qr{sftp_config_messages[\s\S]+editx-manual-sync-form}, 'Tool page renders SFTP prerequisite warnings before the manual action form' );
like( $tool, qr{editx-action-note}, 'Tool page explains disabled manual runs inside the manual action form' );
unlike( $tool, qr{Manual download and import needs valid SFTP sources}, 'Tool page does not duplicate SFTP warnings below the manual action form' );
like( $css, qr{\.editx-manual-sync-form\s*\{[\s\S]+display:\s*block;}, 'CSS keeps the full-chain action button left aligned below the intro text' );
like( $css, qr{\.editx-section-heading\s*\{[\s\S]+display:\s*block;}, 'CSS keeps staged workflow actions left aligned below the intro text' );
like( $css, qr{\.editx-manual-sync-form\s+\.editx-action-note}, 'CSS styles the manual action disabled note' );
like( $css, qr{\.editx-confirm-actions}, 'CSS styles the manual confirmation action row' );
like( $css, qr{\.editx-source-selector}, 'CSS styles the staged source selector' );
like( $css, qr{\.editx-or-separator::before}, 'CSS draws the OR separator rule' );
like( $css, qr{\.editx-stage-table}, 'CSS styles staged workflow tables' );

unlike( $fetch_sftp, qr{set\s+--\s+-q\b}, 'SFTP fetch script does not hide SSH diagnostics with sftp -q' );
unlike( $fetch_sftp, qr{\Q$unofficial_instance_env\E}, 'SFTP fetch script does not depend on unofficial instance environment' );
like( $fetch_sftp, qr{config_file="\$\{EDITX_SFTP_CONFIG:-\$\{1:-\}\}"}, 'SFTP fetch script accepts an explicit config path instead of deriving one from unofficial instance environment' );
like( $fetch_sftp, qr{SSH identity file is not readable by the current user}, 'SFTP fetch script preflights identity file readability' );
like( $fetch_sftp, qr{Local SFTP directory is not writable by the current user}, 'SFTP fetch script preflights local directory writability' );
like( $fetch_sftp, qr{Failed to list remote EDItX files from \$target_user\@\$target_host:\$target_remote_dir}, 'SFTP list failure includes target connection context' );
like( $order_processor, qr{sub\s+getMarcFromKohaFieldCompat\s*\{}, 'Order processor isolates GetMarcFromKohaField compatibility handling' );
unlike( $order_processor, qr{GetMarcFromKohaField\("items\.(?:barcode|homebranch)",\s*''\s*\)}, 'Order processor item call sites do not pass the obsolete framework argument directly' );
like( $order_processor, qr{return\s+C4::Biblio::GetMarcFromKohaField\(\s*\$kohafield,\s*''\s*\)}, 'Order processor keeps the legacy framework argument only inside the compatibility fallback' );

my $run_import = read_file('Koha/Plugin/Fi/KohaSuomi/Editx/cronjobs/runEditXImport.pl');
my $import_runner = read_file('Koha/Plugin/Fi/KohaSuomi/Editx/Procurement/ImportRunner.pm');
my $file_manager = read_file('Koha/Plugin/Fi/KohaSuomi/Editx/Procurement/File.pm');
like( $run_import, qr{exit\(\s*\$result->\{failed\}\s*\?\s*1\s*:\s*0\s*\)}, 'Console import wrapper exits non-zero when import files failed' );
like( $run_import, qr{Failed EDItX file}, 'Console import wrapper prints failed file diagnostics' );
like( $import_runner, qr{sub\s+run_file_paths\s*\{}, 'ImportRunner can import selected explicit file paths' );
like( $file_manager, qr{sub\s+registerFileForImport\s*\{}, 'File manager can register selected staged files before import' );
like( $plugin_pm, qr{use Net::SFTP::Foreign;}, 'Manual staged workflow uses Koha-packaged Net::SFTP::Foreign' );
like( $plugin_pm, qr{Net::SFTP::Foreign->new}, 'Manual staged workflow connects through the Perl SFTP client' );
like( $plugin_pm, qr{sftp_operation => "Net::SFTP::Foreign ls\(\$remote_dir\)"}, 'Manual staged workflow reports the Perl SFTP list operation' );
unlike( $plugin_pm, qr{sub\s+_manual_stage_run_sftp_batch\s*\{}, 'Manual staged workflow has no leftover shell SFTP batch runner' );
unlike( $plugin_pm, qr{sub\s+_manual_stage_sftp_command\s*\{}, 'Manual staged workflow has no leftover shell SFTP command builder' );
unlike( $plugin_pm, qr{sub\s+_manual_stage_parse_sftp_ls_line\s*\{}, 'Manual staged workflow has no leftover shell SFTP listing parser' );
unlike( $plugin_pm, qr{sub\s+_manual_stage_quote_sftp_path\s*\{}, 'Manual staged workflow has no leftover shell SFTP path quoting helper' );
unlike( $plugin_pm, qr{sub\s+_manual_stage_sftp_path_argument\s*\{}, 'Manual staged workflow has no leftover SFTP path argument helper' );
unlike( $plugin_pm, qr{sub\s+_manual_stage_remote_dir_for_listing\s*\{}, 'Manual staged workflow has no leftover remote listing helper' );
unlike( $plugin_pm, qr{sub\s+_manual_stage_parse_sftp_listing_output\s*\{}, 'Manual staged workflow has no leftover listing parser wrapper' );
like( $plugin_pm, qr{sub\s+_manual_stage_filename_matches_pattern\s*\{}, 'Manual staged workflow filters SFTP listings locally by filename pattern' );
like( $plugin_pm, qr{sub\s+_manual_stage_sftp_glob\s*\{}, 'Manual staged workflow has a dedicated SFTP pattern validator' );

done_testing();
